services:
  nginx:
    build : ./requirements/nginx/
    container_name: nginx
    image: nginx
    ports:
      - "443:443"
    restart: always
    networks:
      - inception_network
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
      
  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    image: wordpress
    restart: always
    networks:
      - inception_network
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    depends_on:
      - mariadb
      
  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    restart: always
    networks:
      - inception_network
    volumes:
      - mariadb_data:/var/lib/mysql


      
networks:
  inception_network:
    driver: bridge
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/aakouhar/data/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/aakouhar/data/wordpress
      o: bind
